### PR TITLE
Brenna Stuart

### PR DESCRIPTION
**Pull request by brennacodes**
Here is my Mod 0 final project!

### CODE REVIEW

**Comment by danalvarez5280** [comment]
Good work, a few things tho. You are missing the photos of your calendar. However the video was very thorough so that is okay. However your lesson prep gist is linked to an empty gist. It is under your github account but it is not filled out. If you can fix the link to the completed one within the next day, I will mark as full complete.

**Comment by brennacodes** [comment]
Thank you so much, Dan! I spoke with Amy before submitting and she mentioned that I could just show the system that I'm currently using for those portions since I have already put so much time and effort into it, it's a system that really works for me, and it contains all the information requested in those two sections (calendar, notes system, study system, resources, questions, and much much more). That's why I went into as much detail as I did [under the "Time Management & Lesson Prep" heading](https://github.com/brennacodes/mod-0-project-be/blob/main/final_prep/README.md). You can also view a live view of [a running list of resources that I keep at my website](https://brennacodes.notion.site/Learning-4b390bbc522b4004821ac510d7f0cd9d) (which - surprise surprise - is also populated from my Notion). I also have blog posts there which are my distilled thoughts on new concepts I am learning from Turing lessons, articles, and books that I read.

Anyway, I'm rambling because I'm nervous, but if something has changed, please let me know and I will make sure to fill in any gaps as soon as possible!

**Comment by brennacodes** [comment]
Thanks again @danalvarez5280 ! I appreciate you taking the time to review my work and provide feedback. Amy just let me know I'll be heading to Mod 1 - very excited! 🥳🤗

**Comment by danalvarez5280** [comment]
Wooo! Congrats!

**Pull request closed without merging**
